### ISSUE TITLE
Webpage Scroll Back to Top

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhEC#11]
Design an arrow which can send user to top after scrolling to certain height.

@rajaramdhukhwa Submit it #ASAP

**Comment by rajaramdhukhwa** [comment]
I have send the code of scroll back to top arrow design to shiva kumar sir....

**Comment by ErSKS** [comment]
Congratulations @rajaramdhukhwa, your task is implemented in Khwopa MIS.

**Comment by ErSKS** [comment]
@rajaramdhukhwa Make it as of gmail.com. Specially arrow direction, caret down to scroll page downwards & caret up to scroll page to upwards
