### ISSUE TITLE
Study CSS 3.0 - LESS & SaSS

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhEC#13]
Submit me your conclusion regarding this topic

**Comment by rajaramdhukhwa** [comment]
I found about "saas" is as follows:
Definition:-  Sass (Syntactically Awesome StyleSheets),  is an extension of CSS that adds power and elegance to the basic language. It allows you to use variables, nested rules, mixins, inline imports, and more, all with a fully CSS-compatible syntax.

**Comment by ErSKS** [comment]
See these links:
http://getbootstrap.com/css/#less
http://getbootstrap.com/css/#sass

**Comment by rajaramdhukhwa** [comment]
oh,  Its easy to understand. Thank you sir...

**Comment by rajaramdhukhwa** [comment]
Example of Saas:-
![saas](https://user-images.githubusercontent.com/30016516/28056370-7a02b4b6-663c-11e7-99d9-e4a3661e9225.jpg)

**Comment by ErSKS** [comment]
Good-good, keep going ...

**Comment by rajaramdhukhwa** [comment]
Definition of Less :
Less is a CSS pre-processor, meaning that it extends the CSS language, adding features that allow variables, mixins, functions and many other techniques that allow you to make CSS that is more maintainable, themeable and extendable. Less runs inside Node, in the browser and inside Rhino. The quickest place for first experiments with Less is our online editor.

**Comment by rajaramdhukhwa** [comment]
Installation and procedure of Less:
![less1](https://user-images.githubusercontent.com/30016516/28057626-464a0df0-6640-11e7-85d0-549b6bd26c7e.png)

**Comment by rajaramdhukhwa** [comment]
Less content delivery network (CDN):
![cdnless](https://user-images.githubusercontent.com/30016516/28058700-258cdca4-6641-11e7-8c7f-2a2fa04e3ffb.png)

**Comment by rajaramdhukhwa** [comment]
Video tutorial of CSS with LESS and Sass
https://www.lynda.com/CSS-tutorials/Welcome/107921/115785-4.html
