### ISSUE TITLE
Check Margin-Padding of Web-Pages (http://khec.edu.np)

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhEC#22]
Find-out Webpages those pages which has margin-padding problem.

Reference:
[Ok] http://khec.edu.np/notice/index.html
[Problem] http://khec.edu.np/news/all.html

**Comment by rajaramdhukhwa** [comment]
Margin -padding problem pages in khec are:
http://khec.edu.np/notice/all.html 
http://khec.edu.np/news/all.html
http://khec.edu.np/news/index.html
http://khec.edu.np/blog/detail/5.html
![khec edu np_news_index html](https://user-images.githubusercontent.com/30016516/28256615-e2d1e95c-6ae3-11e7-9dac-2a6c514b9d2d.png)
![khec edu np_notice_all html](https://user-images.githubusercontent.com/30016516/28256628-fc480948-6ae3-11e7-82f9-ef1759f71173.png)
![khec edu np_news_all html](https://user-images.githubusercontent.com/30016516/28256673-59abffae-6ae4-11e7-99d5-4e954033e0b9.png)
![khec edu np_blog_detail_5 html](https://user-images.githubusercontent.com/30016516/28257115-f083affa-6ae7-11e7-8d8e-fcd22456aea9.png)

**Comment by ErSKS** [comment]
Blog/Detail Coorected !
http://khec.edu.np/blog/detail/5

**Comment by ErSKS** [comment]
News/Index redirected to News/All !

**Comment by ErSKS** [comment]
Margin Fixed !
News/All
Notice/All
