### ISSUE TITLE
Resize Students' PP Photo

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/KhEC#9]
@shyambasukala Resize Students' PP Photo for MIS, because it's taking more than 1 GB.

**Comment by ErSKS** [comment]
@shyambasukala It may be automated by using Photoshop !

**Comment by shyambasukala** [comment]
@ErSKS i am trying to automate using photoshop

**Comment by ErSKS** [comment]
**Here is a procedure:**

- Open Photoshop
- Open one PP Photo
![01](https://user-images.githubusercontent.com/5508421/28603559-b4520410-71e4-11e7-8bf0-977d6b4908cc.png)
- Create New Action
![02](https://user-images.githubusercontent.com/5508421/28603593-e3ef4dc2-71e4-11e7-940f-96d9ce8f9497.png)
- Start Record
![03](https://user-images.githubusercontent.com/5508421/28603781-fbf0786e-71e5-11e7-8d75-337d87859942.png)
- View Image Resolution
![04](https://user-images.githubusercontent.com/5508421/28603801-11ad7ddc-71e6-11e7-9fd3-722ecdb0d890.png)
- Reduce Image Resolution
![05](https://user-images.githubusercontent.com/5508421/28603808-1746c7bc-71e6-11e7-9152-b706588302c3.PNG)
- Close an Image
- Stop Action Script
![06](https://user-images.githubusercontent.com/5508421/28603818-26dc58a4-71e6-11e7-9c59-34a8d1e18c99.PNG)
- Go to Automate Batch
![07](https://user-images.githubusercontent.com/5508421/28603833-4a6d4508-71e6-11e7-8743-153736b879e4.png)
- Automate Batch: Set Action, Source & Destination Folder
![08](https://user-images.githubusercontent.com/5508421/28603847-6e5f655e-71e6-11e7-9e57-5d6377cb85d5.png)
- Press Ok
- See the progress
